path:
    folder_Log: "logprocess/"
    akuisisi_log: "akuisisi_log_"
    mqtt_log: "mqtt_log_"
    parsing_log: "parsing_log_"
    raw_log: "data_raw/"
    final_log: "data_final/"
    file_txt: ".txt"
    fileraw_txt: "_raw.txt"
other:
    delimiter: ","
mqtt:
    broker: '202.46.8.100'
    port: 1883
    topic: "test/CBT/DATA/"
    qoslevel: 1
    client_id: "rokatenda2021"
    username: 'rdsPTIK'
    password: 'MosquittoPTIK'
lsAddressList:
    IP:
        - '127.0.0.3'
        - '127.0.0.3'
        - '127.0.0.3'
        - '127.0.0.3'
    PORT:
        - 10001
        - 10002
        - 10003
        - 10004
obuAddressList:
    IP:
        - '127.0.0.1'
        - '127.0.0.1'
        - '127.0.0.2'
        - '127.0.0.2'
    PORT:
        - 10002
        - 10001
        - 10002
        - 10001
TIPEOBU:
    LOKASI:
        - "RKT01"
        - "RKT02"
        - "RKT_"
    OBU:
        - "OBU1"
        - "OBU2"
    SENSOR:
        - "obu1acc"
        - "obu1bpr"
        - "obu2acc"
        - "obu2bpr"
        - "ACC"
        - "BPR"
    TIPESENSOR:
        - "5"
        - "6"
